
# SEO settings
title: "b."
title2: "log()" # default: ""
description: "Technical writings about non-technical things."
keywords: "ben zhang blog"
url: "http://benzy.xyz" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/blog" # apply repo name if use it under gh-pages branch
production_url : "http://benzyx.github.io/blog"
BASE_PATH : "http://benzy.xyz/blog"
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/benzyx/blob
disqus_shortname: "benzy"
twitter_username: "_benzyx"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Ben Zhang"
  job      : "Software Engineer"
  bio      : "I'm a 3rd year CS student at the University of Waterloo."
  thumb    : /images/author.jpg
  email    : frenzybenzy@gmail.com
  url      : benzy.xyz
  github   : http://github.com/benzyx
  twitter  : http://twitter.com/_benzyx
  facebook : https://www.facebook.com/benzyx
  linkedin : http://linkedin.com/in/yxbzhang

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@_benzyx"

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
